### ISSUE TITLE
Start doing code reviews

### ISSUE THREAD

**Issue by lgierth** [ipfs/infra#195]
@victorbjelkholm @hsanjuan
I haven't really been doing PRs on the infrastructure repo, except for the ones that I wanted to bring to people's attention, and even those I merged right away.

Let's start reviewing stuff. Please do pester me with all questions neccessary for review, I'll do my best to add documentation as we go.

This obviously also implies a good way of developing and testing the stuff.

**Comment by hsanjuan** [comment]
How's the document-everything effort going? 

How about make a PR for the documentation first, and then we can ask questions based on that?

**Comment by VictorBjelkholm** [comment]
@lgierth agreed! Good call :+1: 

@hsanjuan I've opened an initial PR about adding some more documentation here: https://github.com/ipfs/infrastructure/pull/197 Please leave some feedback there

**Comment by VictorBjelkholm** [comment]
We should also nail down the processing of merging the changes. Simplest and probably most effective:

1. Person creates PR, suggesting changes
2. People view and accept/reject changes (have a lower limit on how many need to accept?)
3. PR creator merges and deploys changes immediately. 

However, if we have a contribution from a person who does not have access to deploy the changes, we need someone responsible for that deploy.

@lgierth @Kubuxu @hsanjuan Thoughts?

**Comment by hsanjuan** [comment]
@VictorBjelkholm It probably does not hurt to have a project board where we can see issues which are "merged" vs. "deployed" (or labels for each issue). Ideally issues should stay open until they are "deployed". (something github does not help with by closing PRs right after merge).

An alternative is to have a regular deploy cycle (say, every monday we deploy all master no matter what), and we can rotate who is in charge of it so no one forgets the procedures.

**Comment by VictorBjelkholm** [comment]
@hsanjuan personally I prefer to deploy changes as they happen, rather than every monday. I do like the idea of rotating the deploys though, but I know @Kubuxu have some reservations about that as well. I'll let him elaborate.

I like the idea behind having labels for the state of the change very much. Initial suggestion is to have something like this:

* [ ] Need review < when you open the PR
* [ ] Need deploy < after been merged to master and has to be deployed
* [ ] Deployed < Finished

This would make it very explicit and transparent about which state a change is in. Maybe we can use Githubs Project board for this, but should work with just applying labels as well.

@lgierth @hsanjuan @Kubuxu does that flow feel good to you?

**Comment by hsanjuan** [comment]
@VictorBjelkholm that flow feels good to me, we just need to be careful to keep PRs open until the "deployed" tag can be applied to the issue (or somehow keep closed undeployed ones in mind).

A Git tag (like versioning) indicating when a deployment happened would not hurt either.

**Comment by Kubuxu** [comment]
> I do like the idea of rotating the deploys though, but I know @Kubuxu have some reservations about that as well.

I don't recall anything about that. 

> Need deploy < after been merged to master and has to be deployed

This means that PR is closed and master doesn't reflect the state of hosts. This is something I am a bit worried about because I got burned on it once already.

**Comment by VictorBjelkholm** [comment]
> we just need to be careful to keep PRs open until the "deployed" tag can be applied to the issue (or somehow keep closed undeployed ones in mind).

Yeah, I don't think we can keep PRs open after changes have been merged. I think Github also automatically closes a PR as "merged" when you manually merge changes and pushes them.

Maybe we can setup some simple bot to alert us if there is a PR that has the "Need Deploying" label... Just throwing out the idea here.

> A Git tag (like versioning) indicating when a deployment happened would not hurt either.

That's a good idea, a git tag every time a deploy happen, made by the person who deployed it. Does that sound reasonable to the rest of you?

> I don't recall anything about that.

Oh, I'm sorry, I thought I remember a discussion between us regarding who merges/deploys a change, and I thought you had reservations against someone else merging the change, and deploying, but it's very possible I remember incorrectly, sorry for that. 

> This means that PR is closed and master doesn't reflect the state of hosts. This is something I am a bit worried about because I got burned on it once already.

Yeah, I think it's impossible for it to be 100%, there will always be at least a minute of them not being in sync. I think your worry is completely reasonable and my idea of adding the labels is to combat this, so it'll be harder to have master and the hosts not synced, if that makes sense.

**Comment by lgierth** [comment]
We could have a deploybot which watches master, deploys, and posts to a "deploy log" issue in this repo.

**Comment by lgierth** [comment]
The same deploybot could also watch the go-ipfs repo and update the go-ipfs ref here, or integrate with CI/CD.

**Comment by eefahy** [comment]
Closing as it's pretty old and our workflow on making infra changes is being designed now. I generally agree with all the concerns in the thread will ensure that they are represented in how infrastructure changes in the future.
