### ISSUE TITLE
Find easy way to deploy new IPFS versions 

### ISSUE THREAD

**Issue by victorb** [ipfs/infra#206]
Right now, we have to manually change `ipfs/env.sh` to point to a git ref, then deploy the changes.

Any ideas of how we can make it easier?

Comes from: https://github.com/ipfs/infrastructure/pull/204

**Comment by lgierth** [comment]
@whyrusleeping already left a couple of notes in #181

**Comment by eefahy** [comment]
This is happening within the current gateway performance tiger team work
