### ISSUE TITLE
SSL cert for any dnslink page

### ISSUE THREAD

**Issue by lgierth** [ipfs/infra#212]
We've currently got three separate SSL-related things we'd like to have covered.

1. New SSL cert for ipfs.io, from a trustworthy CA (currently StartSSL :/) -- #192 
2. SSL certs for our projects websites (ipld.io, multiformats.io, etc.) -- #203 
3. SSL certs for arbitrary dnslink pages on the gateways.

We can combine all three nicely by automating cert creation through Let's Encrypt (LE).

## On-demand certs

I've looked into solutions for creating certs on-demand during the first TLS handshake,
but it's not currently possible with nginx or any other battle-tested HTTP reverse proxy.

The Traefik and Caddy webservers written in Golang are capable of this,
and we could probably embed the relevant parts into go-ipfs, but:

1. This will be quite a bit of work.
2. We'd no longer have a battle-tested reverse proxy shielding go-ipfs from the internets.

## Dedicated SSL cert setup webtool

The simplest option I've came up with for now, is a webtool which:

- Retrieves a cert for example.com from LE on the click of a button,
- Provides feedback based on repeated requests to https://example.com, and
- Sets up automatic renewal.

The integration with the gateways would be relatively simple:

- Gateways proxy the LE challenge requests (`/.well-known/`) to sslsetup.ipfs.io
- Gateways replicate the certs directory from sslsetup.ipfs.io
- Gateways generate a nginx vhost config for each new cert, and reload the config

So that the workflow is:
1. Put example.com to gateways, either through A/AAAA or CNAME records.
2. Load https://example.com, fails because no cert.
3. Go to sslsetup.ipfs.io and click "Set up SSL".
4. Wait for UI to show SSL Setup completed.
5. Go to https://example.com again, now works.

A few things to not forget:
- Nginx on gateways need appropriately sized vhost buckets.
- Should stress test nginx with tons of vhosts and SSL certs.
- The webtool needs some kind of rate limiting.
- Abuse handling and cert revocation.

**Comment by lgierth** [comment]
https://codeascraft.com/2017/01/31/how-etsy-manages-https-and-ssl-certificates-for-custom-domains-on-pattern/

**Comment by lgierth** [comment]
https://github.com/openresty/lua-nginx-module/#ssl_certificate_by_lua_block

**Comment by lgierth** [comment]
An important observation: all automatic on-demand SSL certs issuing is based on the SNI header value. It must be considered user input, and validated before being sent to Let's Encrypt. Validation could probably be a simple DNS lookup.

It also needs rate limiting to make sure it doesn't hit the Let's Encrypt rate limits.

Another thing to figure out is how to let any ipfs.io gateway trigger SSL cert generation, while having one separate secured service which talks to Let's Encrypt and pushes new/renewed certs to the gateways. Concurrent triggering of the same cert request by multiple gateways, mustn't lead to races or deadlocks. Instead both must be served the new cert once it's available.

We could integrate the whole logic into nginx, via its lua module. There's very cool work in https://github.com/GUI/lua-resty-auto-ssl

**Comment by eminence** [comment]
While Mozilla has started to distrust newer StartCom SSL certs, gentoo has apparently [decided](https://bugs.gentoo.org/show_bug.cgi?id=598072) to distrust all StartCom certs, which breaks the IPFS build process (wgetting from ipfs.io will fail).

Can can be resolved by remerging the `app-misc/ca-certificates` package with the `insecure_certs` USE flag

**Comment by lgierth** [comment]
Update: I'd like someone to implement Consul as a storage provider for lua-resty-auto-ssl: https://github.com/GUI/lua-resty-auto-ssl

We'll already be running Consul on every host for the new gateway infrastructure, so it's a pretty obvious choise. The existing storage providers Redis and Filesystem don't cut it for us.

**Comment by kpcyrd** [comment]
@lgierth I never tried myself, but I think [traefik](https://traefik.io/) is able to talk to consul.

They're also able to request certs on demand and store the certs/acme challenges in consul.

**Comment by lgierth** [comment]
@kpcyrd mh yeah traefik seems more and more viable. I'd really like to stay with nginx, but on the other hand a ton of embedded Lua might not actually contribute to stability either ;)

**Comment by lzsaver** [comment]
> 3. SSL certs for arbitrary dnslink pages on the gateways.

Any progress here?

**Comment by lgierth** [comment]
> > 3. SSL certs for arbitrary dnslink pages on the gateways.
> 
> Any progress here?

We're likely not going to do it -- it's quite a bit of work, and doesn't help in showcasing IPFS since it hides that's being used at all :)

To achieve SSL with a custom domain, I've seen people redirect http://example.com to https://ipfs.io/ipns/example.com

**Comment by kpcyrd** [comment]
If there's interest I would prepare a repo that documents how to get something like this up and running for self-hosting :)

**Comment by lzsaver** [comment]
> **Make It All Secure**
> Now your content is on IPFS and your website is connected to Cloudflare’s gateway. There’s just one more step to make this secure. If you’ve followed all the steps until now, you’ll notice that your website works fine when loaded over HTTP, but is hit with a warning message when you try to load it over HTTPS. That’s because your.website is being redirected to cloudflare-ipfs.com, but Cloudflare’s gateway doesn’t have an SSL certificate for your.website. The good news is that Cloudflare can fix that.
> 
> Cloudflare will issue you a free SSL certificate for your.website, which allows users to load https://your.website. All you have to do is go to cloudflare-ipfs.com and scroll to the bottom, where it says “Connecting Your Website.” Enter your domain into the text box and click Submit. When you click Submit the certificate issuance will begin. When it’s done, a message will appear indicating that the process has been completed and your certificate is in place. These certificates will auto-renew, so once you’ve completed this step, you’ll never need to worry about certificates again.
> 
> With these DNS records and the certificate in place, any request to your domain, https://your.website will be automatically re-routed to https://cloudflare-ipfs.com/ipfs/<hash_of_content> behind the scenes. Visitors to your website will never have to worry about the fact that your content is stored in IPFS or deal with hashes. They just go to your domain and the content loads.

Source: https://developers.cloudflare.com/distributed-web/ipfs-gateway/connecting-website/
