### ISSUE TITLE
Set CAA records

### ISSUE THREAD

**Issue by ghost** [ipfs/infra#298]
https://blog.qualys.com/ssllabs/2017/03/13/caa-mandated-by-cabrowser-forum

> Certification Authority Authorization (CAA), specified in RFC 6844 in 2013, is a proposal to improve the strength of the PKI ecosystem with a new control to restrict which CAs can issue certificates for a particular domain name. Although CAA had been in the proposed-standard state for more than 4 years, there was little obvious happening until very recently, with only a hundred or two hundred sites adopting it. But that’s going to change, because the CA/Browser Forum recently voted to mandate CAA support as part of its certificate issuance standard Baseline Requirements. The changes will become effective in September 2017.

tl;dr we'd set CAA headers on our DNS zones, similar to this:

```
example.org. CAA 128 issue "letsencrypt.org"
```

DNSimple supports these, so it should be pretty easy. We only need to migrate DNS for ipfs.io and ipfs.team from DigitalOcean to DNSimple first.

**Comment by mburns** [comment]
This is live.

```
$ dig +short CAA ipfs.io
0 issue "letsencrypt.org"
0 issue "pki.goog"
0 issuewild "letsencrypt.org"
```
