### ISSUE TITLE
Auto-convert root paths for /ipfs and /ipns using nginx for ipfs.io HTTP gateway

### ISSUE THREAD

**Issue by kyledrake** [ipfs/infra#318]
Okay, so load this site:

https://ipfs.io/ipns/fauux.neocities.org/

Then load this site:

https://fauux.neocities.org

Notice how the first one doesn't load correctly, but the second one does.

This is because of the root path issue. In a nutshell, the site requests /asset.css, but within the context of ipfs.io, this means it tries to access ipfs.io/asset.css, which 404's.

So here's my idea:

With the nginx logic on the gateway, check the referrer header. If it matches /ipfs/ or /ipns/, then use nginx to rewrite the root path to load the asset from the relative path.

So for example, nginx receives a request to /styles.css from /ipns/example.org with an HTTP referer header "/ipns/example.org", and internally rewrites it to load /ipns/example.org instead of failing with a 404 and breaking a lot of web sites.

**Comment by kyledrake** [comment]
Maybe needs some shoe polish, but this seems to do it:

``` nginx
server {
  listen 80;
  server_name example.com;

  location /ipfs/ {
    proxy_pass http://127.0.0.1:8080;
  }

  location /ipns/ {
    proxy_pass http://127.0.0.1:8080;
  }

  location / {
    if ($http_referer ~ (\/ipfs\/.+\/|\/ipns\/.+\/)) {
      set $new_root_path $1;
    }
    rewrite \/(.*)$ $new_root_path/$1 last;
  }
}
```

**Comment by lgierth** [comment]
:+1: I feel like this is something we'd want in go-ipfs too if we can get it right. Removes a sharp UX edge.

I think the code you posted might have a problem when clicking on a link e.g. from https://ipfs.io/ipfs/QmFoo to a dnslink'd https://example.net/path -- it'd get rewritten to /ipfs/QmFoo/path. Maybe it helps to check the referrer against the host header.

**Comment by lgierth** [comment]
I wonder how this would play with e.g. `wget --mirror`

**Comment by kyledrake** [comment]
@lgierth I'm not sure I understand the problem here. I tried a link via https://ipfs.io/ipfs/QmVVDuTiesYPcHnvgAAskJYAb9DUxUFKtLFhrrP4v4miiw to http://example.com/ipns/fauux.neocities.org and it worked fine?

**Comment by meteorplus** [comment]
Guys How do I change the ipfs/$hash path to something/$hash ? #5342
