### ISSUE TITLE
Have bootstrap nodes with ports different from 4001

### ISSUE THREAD

**Issue by victorb** [ipfs/infra#369]
All bootstrap nodes are using port 4001. We should have some of the bootstrap nodes listen on different ports as well, in case 4001 is not working for some reason.

Some suggestions: `80`, `443`, `53`, `22` and `110`

From https://github.com/ipfs/ipfs/issues/221

**Comment by lgierth** [comment]
We do have /wss nodes on port 443: https://github.com/ipfs/js-ipfs/blob/master/src/core/runtime/config-browser.json

But there's certainly more we can do, e.g. libp2p/libp2p#18

**Comment by wmitsuda** [comment]
+1 I've just stumbled upon this problem today and after debugging my connection I've reached this issue here. And yes, I'm in a coffee shop right now :)

**Comment by ribasushi** [comment]
@Stebalien @jacobheun: this issue is super-old ( originally opened a the start of 2017 ). Can we tie this as a hard-req on the new-bootstrapper deploys, so it doesn't slip anymore?

**Comment by Stebalien** [comment]
The new bootstrappers can listen on any port, or even multiple ports. We could even change them randomly every day.

**Comment by ribasushi** [comment]
@Stebalien yes, the point is that they *have* to listen on "well known ports". Otherwise temporary IPFS nodes behind dumb-coffee-shop firewalls permitting only `:80` and `:443` and *nothing* else can never join the network.

**Comment by ribasushi** [comment]
> ~the point is that they have to listen on "well known ports"~

the point is that **at least few nodes** have to listen on "well known ports"...

**Comment by ribasushi** [comment]
@mburns ( continuing a conversation from elsehwere ) while the bootstrap nodes indeed listen on 80/443, this doesn't help an initial bootstrapper, as the only outgoing connections would be to 4001. The state as of the 0.5 rc on a fresh init is:
```
 grep -i bootstrap -A2 ~/.ipfs/config 
  "Bootstrap": [
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt",
    "/ip4/104.131.131.82/tcp/4001/p2p/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb"
  ],
```
```
host -t TXT _dnsaddr.bootstrap.libp2p.io 
_dnsaddr.bootstrap.libp2p.io descriptive text "dnsaddr=/dnsaddr/ams-2.bootstrap.libp2p.io/tcp/4001/ipfs/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb"
_dnsaddr.bootstrap.libp2p.io descriptive text "dnsaddr=/dnsaddr/ewr-1.bootstrap.libp2p.io/tcp/4001/ipfs/QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa"
_dnsaddr.bootstrap.libp2p.io descriptive text "dnsaddr=/dnsaddr/nrt-1.bootstrap.libp2p.io/tcp/4001/ipfs/QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt"
_dnsaddr.bootstrap.libp2p.io descriptive text "dnsaddr=/dnsaddr/sjc-1.bootstrap.libp2p.io/tcp/4001/ipfs/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN"
```

i.e. the original issue described in this ticket is still outstanding without the dns changes...

**Comment by RubenKelevra** [comment]
I think 443 is the best solution. We use TLS and QUIC which both run on 443 for centralized web traffic.

I do run my nodes on 443 for the same reason.

**Comment by mburns** [comment]
Bootstrap nodes now announces `/tcp/443/wss/` as part of the `boostrap.libp2p.io` dnsaddr list (and `/udp/4001/quic/`, for that matter).

Going to call this complete. Reopen if it this solution is insufficient.
