### ISSUE TITLE
Deploy libp2p-nodetrust to the galaxy!

### ISSUE THREAD

**Issue by mkg20001** [ipfs/infra#384]
[Libp2p nodetrust](https://github.com/mkg20001/libp2p-nodetrust) is a tiny libp2p module that allows browsers to directly connect to websocket-capable IPFS/libp2p nodes using letsencrypt certificates and custom DNS in order to move some of the load away from the bootstrap servers and make the network more decentralized.

I did a demo on the all-hands-call March, 5th explaining what it does and ideally want it to be deployed on the libp2p infrastructure

// cc @VictorBjelkholm @diasdavid 

Edit: Demopage: https://libp2p-nodetrust.tk/demo

**Comment by mkg20001** [comment]
@lgierth @VictorBjelkholm what needs to be done for this to happen?

**Comment by mburns** [comment]
per Slack, it sounds like this was experimented with but ran into rate-limiting issues.

Now that LE supports wildcard certs, I think we can solve that problem.

**Comment by thattommyhall** [comment]
https://github.com/libp2p/go-libp2p/issues/1360 is where this will happen!!!
