### ISSUE TITLE
Grafana.com IPFS Dashboards

### ISSUE THREAD

**Issue by victorb** [ipfs/infra#399]
From https://github.com/ipfs/go-ipfs/issues/4934

> There is Prometheus metrics endpoint, but no grafana ipfs specific dashboard.
> Will be nice to see IPFS dashboard, deployed https://grafana.com/dashboards.

Reply from me:
> Indeed, this is a very good point. We do have dashboards but they are currently just deployed within our metrics.ipfs.team network which is private. We want to move into having public dashboards and we'll make sure to publish them on grafana.com/dashboards once we do.

**Comment by lgierth** [comment]
Clarification, this is not about publicly accessible dashboards for IPFS nodes we run, but about prebuilt IPFS-focused dashboards that can be installed through Grafana's module system.

**Comment by Ironman-Jason** [comment]
@victorb , can we have a first glance of the dashboard json meta which used in your metrics.ipfs.team network?

**Comment by victorb** [comment]
@Ironman-Jason this might be something @eefahy or @mburns could help you out with, as I'm not super familiar with our new metrics setup.

**Comment by Ironman-Jason** [comment]
@victorb, @eefahy, @mburns, thanks a lots.

**Comment by eefahy** [comment]
Hi @Ironman-Jason [Here's the json](https://gist.github.com/eefahy/52c3df180e67a2fc4520a7be1dc394b7) for our IPFS dashboards.
