### ISSUE TITLE
How to use dentlist.conf in ipfs

### ISSUE THREAD

**Issue by konyzulphurea** [ipfs/infra#418]
https://github.com/ipfs/infrastructure/blob/master/ipfs/gateway/denylist.conf

Since It is new, And There are so many windows users. 

I like to know, how to use the list so can prevent some unwelcomed material pass our gateway since ipfs.io applies that, and We like to include it.

**Comment by eefahy** [comment]
@konyzulphurea That denylist is a config file in our nginx setup. You're welcome to use it as you see it.

Closing as I'm not sure there's much we can do to help here but please do reopen if this answer isn't sufficient.
