### ISSUE TITLE
better content-type for wasm on public gateways

### ISSUE THREAD

**Issue by eminence** [ipfs/infra#433]
I'd like to use ipfs to host small applications written in web assembly.  Currently the public ipfs gateways are serving webassembly files (.wasm extension) with the `application/octet-stream` content-type.  However browsers require that web assembly files be served with the `application/wasm` content-type.

Would it be possible to reconfigure the ipfs gateways to use the correct content type for .wasm files?

**Comment by lgierth** [comment]
You'll have to take this up with go-ipfs :)

**Comment by mburns** [comment]
discussion has moved to https://github.com/ipfs/go-ipfs/issues/5520
