### ISSUE TITLE
wss://ws-star.discovery.libp2p.io is down

### ISSUE THREAD

**Issue by mccoysc** [ipfs/infra#436]
wss://ws-star.discovery.libp2p.io is down

**Comment by jacobheun** [comment]
It looks like there is an ongoing outage of ws-star.discovery.libp2p.io over the past several days. We've had intermittent outages in the past, but this outage appears to have been going on for several days.

**Comment by alanshaw** [comment]
ping @ipfs/infra

**Comment by victorb** [comment]
Solved and added additional monitoring + alerting for the future.
