### ISSUE TITLE
Are the preload nodes connected to the gateway nodes?

### ISSUE THREAD

**Issue by alanshaw** [ipfs/infra#448]
I added a file to js-ipfs and it was preloaded at:
https://node0.preload.ipfs.io/ipfs/QmQeEyDPA47GqnduyVVWNdnj6UBPXYPVWogAQoqmAcLx6y

However, the same hash does not seem to be available on the gateway:
https://ipfs.io/ipfs/QmQeEyDPA47GqnduyVVWNdnj6UBPXYPVWogAQoqmAcLx6y

**Comment by klueq** [comment]
`node0` gives me a 400, but `ipfs.io` works.

**Comment by eefahy** [comment]
Closing in favor of https://github.com/ipfs/infra/issues/463 - if that isn't sufficient to satisfy this request, please reopen this issue.
