### ISSUE TITLE
Redirect https://conf.ipfs.io/ to form

### ISSUE THREAD

**Issue by daviddias** [ipfs/infra#451]
Right now, https://conf.ipfs.io/ leads to 404. Can you add a redirect to https://docs.google.com/forms/u/1/d/e/1FAIpQLSfJVVPwvp6RY3MUg1zAVl1g_5y2nGb7WJIMI1Hs6glzm7FLHQ/viewform?usp=send_form ? Thaaank you!

**Comment by kyledrake** [comment]
G2G
