### ISSUE TITLE
Getting 'error in createRecord'

### ISSUE THREAD

**Issue by PedroMiguelSS** [ipfs/infra#454]
Hi there!

I'm having trouble deploying new versions of [js.ipfs.io](https://github.com/ipfs/js.ipfs.io):

<img width="1358" alt="screen shot 2018-11-16 at 10 53 37" src="https://user-images.githubusercontent.com/11461281/48617748-3a268c00-e98f-11e8-942d-86d957a53a7f.png">

I tried replaying and rebuilding it several times but the same error occurs.

**Comment by daviddias** [comment]
This is blocking getting `js.ipfs.io` service worker gateway fixed.

**Comment by daviddias** [comment]
ref: https://github.com/ipfs/js.ipfs.io/issues/199

**Comment by lidel** [comment]
cc  https://github.com/ipfs/infrastructure/issues/449 (same error for `explore.ipld.io`)

**Comment by eefahy** [comment]
Looking into this now

**Comment by mburns** [comment]
@eefahy has updated the shared pipeline library, so new changes should use the correct script/API now.

When we re-ran [the website job](https://ci.ipfs.team/blue/organizations/jenkins/IPFS%2Fjs.ipfs.io/detail/master/21/pipeline) it failed having not discovered the new changes.

Without wanting to get too deep into Jenkins and risk further breaking things, I made a no-op change. https://github.com/ipfs/js.ipfs.io/pull/200

If merged, it will be reverted. This should just test the (dev) deploy cycle to pick up all the changes.
