### ISSUE TITLE
Support for cypress on website jenkins-libs

### ISSUE THREAD

**Issue by PedroMiguelSS** [ipfs/infra#455]
Hi there!

On [js.ipfs.io](https://github.com/ipfs/js.ipfs.io) we are using the [website library function](https://github.com/ipfs/jenkins-libs#website-preview-and-deployment-hugo-only) for Jenkins CI, as you can see in [ipfs/js.ipfs.io/ci/Jenkinsfile](https://github.com/ipfs/js.ipfs.io/blob/master/ci/Jenkinsfile).

In the context of [ipfs/js.ipfs.io#199](https://github.com/ipfs/js.ipfs.io/issues/199), we added tests to the `service-worker-gateway` usage, in order to avoid similar problems. We are using [cypress](https://github.com/cypress-io/cypress) to achieve that. 

Our goal is to run the tests on the CI. Accordingly, after the build step we should spawn a server, which using the `/public` folder would run the tests. In our point of view, it should run on a different stage (a post-build one) instead of running on the build stage.

Here is what we are trying to run: 

```console
start-server-and-test serve http://localhost:9000 cy:run
```

After taking a look at [website library function](https://github.com/ipfs/jenkins-libs#website-preview-and-deployment-hugo-only) we think that having an `option` like: 

```
website([
   (...)
   cypress: 'start-server-and-test serve http://localhost:9000 cy:run'
])
```

would be one possible solution to keep it simple. 

You can check [here](https://docs.cypress.io/guides/guides/continuous-integration.html#What-is-supported) what's needed to run `cypress` on CI.

**NOTE:** For now, we have the tests running on the `pre-push` hook. But it's only a temporary solution until we get it running on the CI.

//cc @vasco-santos

**Comment by PedroMiguelSS** [comment]
[ipfs/js.ipfs.io#199](https://github.com/ipfs/js.ipfs.io/issues/199) will be blocked until we get a solution for this.

**Comment by daviddias** [comment]
Ping @ipfs/infra

**Comment by scout** [comment]
Please see https://github.com/ipfs/infra/issues/474#issuecomment-458686511 for my thoughts re: website deployments via Jenkins

**Comment by scout** [comment]
Jenkins has been shut down
