### ISSUE TITLE
Host npm-on-ipfs EC2 instance & S3 bucket in the same AWS region

### ISSUE THREAD

**Issue by achingbrain** [ipfs/infra#456]
The EC2 instance being used by npm-on-ipfs is hosted in eu-west-2 but the S3 bucket it's using is in us-west-1.  Because it's using [`datastore-s3`](https://github.com/ipfs/js-datastore-s3) to persist it's IPFS repo, this causes increased latency making everything slower.

These need to be hosted in the same region.

**Comment by eefahy** [comment]
I've made a new private repo to track the infra resources for this & gave the instance a role that has access to the S3 bucket. You will have to update anywhere you manually set a key id and secret to allow for the sdk to go get credentials on the instance role automagically.

While working on this, I ran the deploy script a couple of time to test out not setting the key env vars. When I ran deploy.sh to get it back to its original state the box wedged. I can't ssh onto it and https://registry.js.ipfs.io/ can't be reached. sigh... Tomorrow I'll write a boot script for the machine to deploy the registry repo on startup.

**Comment by eefahy** [comment]
@achingbrain I noticed that your using the VM's IP to configure the service but it's not assigned a static IP. I made an issue [here](https://github.com/protocol/npm-on-ipfs-infra/issues/1) for that work and hope to get to it this coming week.

Closing this now but reopen or make another ticket if you continue to see issues
