### ISSUE TITLE
Re-enable CI for js-cid

### ISSUE THREAD

**Issue by vmx** [ipfs/infra#460]
Probably due to moving js-cid from `ipld` to `multiformats` the CI got lost. Can you please configure https://github.com/multiformats/js-cid/ to have Jenkins again? It's a normal JavaScript project, nothing special is needed.

PS: I hope it's the right issue tracker for such tasks.

**Comment by eefahy** [comment]
I see that's it's enabled on the Jenkins side: https://ci.ipfs.team/job/Multiformats/job/js-cid/

**Comment by victorb** [comment]
It was already enabled when the move happened! Job is here: https://ci.ipfs.team/job/Multiformats/job/js-cid/

What was lost though, was the `CI` team having write access to js-cid repo, so the status commit never appeared. I've added the `CI` team now so it should work properly.

**Comment by eefahy** [comment]
@victorb by `CI` team do you just mean that https://github.com/ImmutableJenkins needs write access to all repos that Jenkins will run tests for?

**Comment by vmx** [comment]
@victorb Can you tell me again how I trigger a job on a PR where it wasn't started yet?

**Comment by victorb** [comment]
@eefahy no, each organization has a `ci` team (which ImmutableJenkins is part of) that needs to have the `write` permission to the repositories.

@vmx hm, not sure what you mean exactly. If a PR hasn't been build, you can try going to https://ci.ipfs.team/job/Multiformats/job/js-cid/ and then clicking "Scan Repository Now" on the left to force a rescan. Jenkins should automatically pick up the PRs within seconds though.

**Comment by vmx** [comment]
>  If a PR hasn't been build, you can try going to https://ci.ipfs.team/job/Multiformats/job/js-cid/ and then clicking "Scan Repository Now" on the left to force a rescan.

@victorb That's exactly what I was asking for. Thanks a lot!
