### ISSUE TITLE
Create a new signalling server for IPFS Share Files

### ISSUE THREAD

**Issue by fsdiogo** [ipfs/infra#461]
The @ipfs/gui-team has been discussing using a signalling server for the [IPFS Share Files](https://github.com/ipfs-shipyard/ipfs-share-files) app. You can read about the why [in this issue](https://github.com/ipfs-shipyard/ipfs-share-files/issues/63).

TL;DR: peer discovery is badly hurting the usability of the app. While this isn't fixed we thought of using a signalling server to help out.

As the app release for production is soon to be, does it makes sense to create a dedicated server for it? Or is it enough using one of the existing ones?

**Comment by eefahy** [comment]
Hi @fsdiogo - I read through the linked issue and related issues but am not sure I fully understand the implications of running a dedicated server over using existing ones (which are those exactly?) I would be happy to go see how much the existing servers are being utilized and make a judgement as to if they can handle more traffic if that's your concern.

**Comment by olizilla** [comment]
We talked this through on our weekly catch up and @eefahy and I had a good conversation about it.

The short version is we need create documentation and a story around share that clearly explains the goals / perf expectations that users should have, and the ipfs config and any points of centralisations or infrastrucure required to meet those expectations today. 

With that we can drill in to what our expectations are of the preload nodes. @eefahy made the good point that id the preload nodes are working as intended, we may not need to add a ws-star discovery and transfer node into as well. We can use this project as an opportunity to work with infra to help define things like "what is the average and minimum time a block will be available from a preload node" which can be used to define the hosting strategy for the preload nodes, and how do we signal to app developers when the preload nodes are experinencing a spike in trafffic that might push that time down (_preload will pin blocks until they exceed their configured `storageMax` which will trigger GC, which will clear out older blocks, so at busy times the min storage time_ could drop below the advertised minimum.) or what should happen if those nodes are offline.

It works both ways too; infra can call out issues with the current IPFS architecture that make it harder to set up good Site Reliabilty practices (clustering, load balance, decoupling of resources from specific instances _looking at you peerId in the preload server definitions_)

The goal is not to release share.ipfs.io as soon as possible, but to make sure that when we do it is an explary IPFS based service, and can be used as an educational resource, and a set of recommendations to app builders and the community. It's worth doing this well, even it means delaying our release for it.

@fsdiogo I'll work with you on an outline for this work, and we'll ping @eefahy and @daviddias for feedback on it as we go.
