### ISSUE TITLE
Redirect /ipfs/ and /ipns/ traffic from preload nodes to the Gateway

### ISSUE THREAD

**Issue by eefahy** [ipfs/infra#463]
Carried over from https://github.com/ipfs/infra/issues/448 - since we only expose the api endpoint at the preload nodes, when one requests a /ipfs/hash they get a 404. In order to field the request cleanly, we should redirect those requests to the gateway.

**Comment by olizilla** [comment]
@lidel you triggered this conversation in https://github.com/ipfs/infra/issues/448#issuecomment-436235357

given that preload nodes have not functioned as gateways for some time, shouldn't we just leave it now... folks should not be using gateway urls that point at the preloads, and if we start redirecting them, then they may continue or restart using preload nodes with an ipfs path which we don't want.

**Comment by lidel** [comment]
@olizilla agreed. it made sense year ago (right after we blocked it) but as you noted we did not support gateway requests on preload nodes for over a year, I believe this should be closed as nofix.

**Comment by mburns** [comment]
closing per discussion.
