### ISSUE TITLE
Update SXG Origin Trial Token on HTTP Gateway

### ISSUE THREAD

**Issue by lidel** [ipfs/infra#465]
> This is continuation of  https://github.com/ipfs/infra/issues/453 and https://github.com/ipfs/in-web-browsers/issues/121

I renewed [our participation](https://github.com/ipfs/infra/issues/453) until Jan 25, 2019, but we need to update `Origin-Trial` header to new value:

```
Apz+MZlH/rQM6+d3sDPQYouRZMaRgp9YyhKhp3Gz527Zi3rCyt+vgNoPgfNkMTp408APUc+fxEAs5+MB7WgoHA4AAABeeyJvcmlnaW4iOiJodHRwczovL2lwZnMuaW86NDQzIiwiZmVhdHVyZSI6IlNpZ25lZEhUVFBFeGNoYW5nZU9yaWdpblRyaWFsIiwiZXhwaXJ5IjoxNTQ4NDIzNDA0fQ==
```

**Note:** this is time-sensitive (cc @kyledrake), as the old one will expire in one week:

>  Thanks for your participation in the origin trial for Signed HTTP Exchange! As a reminder, we previously issued a token as follows:
> Origin: https://ipfs.io
> Issued: 2018-11-08
> Expires: 2018-12-20
> 
> You’ll need to renew your registration in order to continue using the feature on your site. If you do not renew, your site will lose access to the feature on 2018-12-20. Upon renewal, we’ll generate a new token to replace the expiring token on your site. 

### References

- [[Meta] Signed HTTP Exchanges and WebPackage](https://github.com/ipfs/in-web-browsers/issues/121)
- [Signed HTTP Exchanges: Chrome Origin Trials](https://docs.google.com/document/d/1P1t-ZGb216JLxZiWQOi-g9oOx50f7PVRE_h4TjkJkFM/view) (living document)
- [Origin Trial Token Validator](https://googlechrome.github.io/OriginTrials/check-token.html) (to ensure token is correct and did not expire yet)

**Comment by kyledrake** [comment]
Done, thanks!
