### ISSUE TITLE
User reported issues connecting to dist.ipfs.io

### ISSUE THREAD

**Issue by daviddias** [ipfs/infra#471]
Found https://stackoverflow.com/questions/54169429/i-get-an-error-when-i-execute-npm-install-go-ipfs/54180368#54180368.

I tried it myself it is working now. Do we have any stats of the service being down recently?

**Comment by kyledrake** [comment]
Their DNS resolver is resolving dist.ipfs.io to a Facebook IP for some weird reason. See https://stackoverflow.com/a/54180561/3965348 (Error: connect ECONNREFUSED 31.13.80.1:443)

I think we can close this unless he comes back with additional information. I don't think this is on our end.
