### ISSUE TITLE
migrate discourse (discuss.ipfs.io) from self-hosted to hosted

### ISSUE THREAD

**Issue by eefahy** [ipfs/infra#472]
Things to do:
- review current storage needs and admin accounts
- contact discourse folks about migration

ref: https://payments.discourse.org/pricing

**Comment by victorb** [comment]
Yay \o/!

On that topic, we should reach out to @erlend-sh as he helped us with getting Discourse in the first place, with the migration to discuss.ipfs.io and he even has an account on our forum. He's a Community Advocate over at Discourse.

**Comment by daviddias** [comment]
@eefahy can we have an ETA on this migration? It would be one more nice thing to remove from Infra's team plate

**Comment by eefahy** [comment]
@daviddias I agree it would be great to remove from our plate but it’s a P2 atm and therefore pretty far down our list of things to get done.

@victorb do you have any bandwidth to take this one on?

**Comment by mburns** [comment]
I'm happy to move this forward. To do the migration, I need access to the machine and/or the web ui.

@lgierth can you add [my user/key](https://github.com/mburns.keys), please? I don't see any credentials in 1pass to let me do this myself.

@daviddias could you or someone else grant me Admin permissions on the forum? Per [this guide](https://meta.discourse.org/t/move-your-discourse-instance-to-a-different-server/15721), things like backups can only be triggered by admin-level users. I'm https://discuss.ipfs.io/u/mburns

**Comment by lgierth** [comment]
> @lgierth can you add [my user/key](https://github.com/mburns.keys), please? I don't see any credentials in 1pass to let me do this myself.

Yeah added both you and scout :+1:

**Comment by scout** [comment]
ping @daviddias - can @mburns get admin access to the forum please?

**Comment by mburns** [comment]
I've granted myself admin access via the `rake` task.

I've reached out to Discourse' sales people, and apparently Discourse will handle the migration if we go from self-hosted to hosted. Easy-peasy.

The migration itself looks easy. TODO

- [ ] announce migration / planned maintenance window on the forum
- [ ] stop forum
- [ ] backup/export
- [ ] Take DO snapshot
- [ ] import on hosted plan
- [ ] update DNS
- [ ] ✋  high fives all around ✋

**Comment by mburns** [comment]
Migration complete.

![](https://media.giphy.com/media/l0O9zenhV72Yrm4Pm/giphy.gif)

**Comment by daviddias** [comment]
👏🏽👏🏽👏🏽! Thank you for shipping this!
