### ISSUE TITLE
dist.ipfs.io unusually slow

### ISSUE THREAD

**Issue by mkg20001** [ipfs/infra#475]
Currently trying to download armhf go-ipfs, download is staling and progressing only slowly
```
maciej@mkg-lenovo:/tmp/tmp.5EifRRBnTG$ wget https://dist.ipfs.io/go-ipfs/v0.4.18/go-ipfs_v0.4.18_linux-arm.tar.gz
--2019-01-27 14:28:51--  https://dist.ipfs.io/go-ipfs/v0.4.18/go-ipfs_v0.4.18_linux-arm.tar.gz
Auflösen des Hostnamens dist.ipfs.io (dist.ipfs.io) … 2602:fea2:2::1, 209.94.90.1
Verbindungsaufbau zu dist.ipfs.io (dist.ipfs.io)|2602:fea2:2::1|:443 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 200 OK
Länge: 10933477 (10M) [application/gzip]
Wird in »go-ipfs_v0.4.18_linux-arm.tar.gz« gespeichert.

go-ipfs_v0.4.18_linux-arm.tar.gz     47%[==============================>                                   ]   5,00M  --.-KB/s    ETA 69s    ^C
```

The portion of the download that the node I'm downloading from has already retrieved downloads very quickly, while the rest of the file takes a lot more time (and is mostly staled)

**Comment by scout** [comment]
dist.ipfs.io is hosted via the gateway so I'm guessing that this is continued issues related to https://github.com/ipfs/infra/issues/467 - closing this issue in favor of #467 but please reopen if you disagree
