### ISSUE TITLE
Redirect HTTP to HTTPS on dweb.link

### ISSUE THREAD

**Issue by lidel** [ipfs/infra#477]
HTTPS was added in https://github.com/ipfs/infra/issues/391, and HSTS header is set correctly so all the following HTTP requests get upgraded to HTTPS :ok_hand: 

```bash
$ curl -Is https://bafkreigh2akiscaildcqabsyg3dfr6chu3fgpregiymsck7e7aqa4s52zy.ipfs.dweb.link/                                    1 ~
HTTP/2 200      
(...)
strict-transport-security: max-age=31536000; includeSubDomains; preload

```

However, if the very first request goes over HTTP, it ends with 404:

```bash
$ curl -Is http://bafkreigh2akiscaildcqabsyg3dfr6chu3fgpregiymsck7e7aqa4s52zy.ipfs.dweb.link/                                       ~
HTTP/1.1 404 Not Found
```

Let's redirect to `https://` to remove any surprises. :bomb:

**Comment by scout** [comment]
Will do! sorry about that.

**Comment by scout** [comment]
Done.
