### ISSUE TITLE
ipfs.io gateway returns internalWebError but cloudflare gateway doesn't

### ISSUE THREAD

**Issue by andrew** [ipfs/infra#480]
Not a showstopper issue for me, just a weird bug I noticed with some gateways but not others that wasn't very clear, @scout asked me to open an issue so it can be kept track of.

When attempting to view a folder (QmThJ4k554iT3B7SZonmVMwspHALiHGThhqaem7nij1wQD) via IPFS on the gateway, some gateways seem to error with `internalWebError: operation not supported` others in another and some work as expected. 

[https://ipfs.io/ipfs/QmTh...](https://ipfs.io/ipfs/QmThJ4k554iT3B7SZonmVMwspHALiHGThhqaem7nij1wQD): `internalWebError: operation not supported`

[https://ipfs.infura.io/ipfs/QmTh...](https://ipfs.infura.io/ipfs/QmThJ4k554iT3B7SZonmVMwspHALiHGThhqaem7nij1wQD): `internalWebError: operation not supported`

[https://ipfs.jes.xxx/ipfs/QmTh...](https://ipfs.jes.xxx/ipfs/QmThJ4k554iT3B7SZonmVMwspHALiHGThhqaem7nij1wQD) and [https://cloudflare-ipfs.com/ipfs/QmTh...](https://cloudflare-ipfs.com/ipfs/QmThJ4k554iT3B7SZonmVMwspHALiHGThhqaem7nij1wQD) work as expected: 

<img width="1234" alt="Screenshot 2019-03-21 at 18 20 27" src="https://user-images.githubusercontent.com/1060/54775484-080b8c00-4c06-11e9-9591-535bab036715.png">

**Comment by andrew** [comment]
I wonder if this is related to the use of `--raw-leaves`

**Comment by scout** [comment]
I looked more into this but still confused. The cloudflare and jes gateways load the root object fine as you noted, but are printing `ipfs cat /ipfs/QmTh.../ubuntu: cannot currently read symlinks` however our and infura's gateway loads that fine.

see:
[https://ipfs.jes.xxx/ipfs/QmTh.../ubuntu](https://ipfs.jes.xxx/ipfs/QmThJ4k554iT3B7SZonmVMwspHALiHGThhqaem7nij1wQD/ubuntu)
[https://ipfs.infura.io/ipfs/QmTh.../ubuntu](https://ipfs.infura.io/ipfs/QmThJ4k554iT3B7SZonmVMwspHALiHGThhqaem7nij1wQD/ubuntu)

Does that make any sense to you?

**Comment by andrew** [comment]
Yeah ubuntu is a symlink

**Comment by andrew** [comment]
Looks like it's related to this issue: https://github.com/ipfs/go-ipfs/issues/6203

**Comment by scout** [comment]
@andrew since this is most likely a software issue can this issue be closed?

**Comment by andrew** [comment]
Yeah, it seems like it'll solve itself as the different gateways upgrade to the latest versions of IPFS.
