### ISSUE TITLE
Fix HTTPS on  dnslink.dev

### ISSUE THREAD

**Issue by lidel** [ipfs/infra#481]
1. The certificate  at https://dnslink.io is only valid for the following names: *.dwebops.net, dwebops.net
2. https://dnslink.dev does not load at all

**Comment by lidel** [comment]
@mburns this is still broken, needs to be reopened

**Comment by mburns** [comment]
https://dnslink.io/ is loading without cert errors.

**Comment by olizilla** [comment]
@lidel can you confirm what https://dnslink.dev is intended to be used for? Just a redirect to https://dnslink.io ? I'm not clear what the motivation is to make it work?

**Comment by olizilla** [comment]
@lidel can you confirm what dnslink.dev is supposed to do? I'm inclined to just leave it unconfigured rather than have yet another redirect. Did it used to do something?

**Comment by lidel** [comment]
@olizilla iirc  @jbenet wanted  `dnslink.dev` instead of `.io`, but at the time we had `.io` already registered so it

I don't have any strong feelings about this, but if we don't intent to support `dnslink.dev` then it should return 404 instead of TLS failure :^)
