### ISSUE TITLE
Enable HTTP/2 on preload/delegate nodes

### ISSUE THREAD

**Issue by lidel** [ipfs/infra#489]
## Problem

HTTP/2 is not supported on preload/delegate hostnames:

- `node0.preload.ipfs.io`, `node1.preload.ipfs.io`
- `node0.delegate.ipfs.io`,`node1.delegate.ipfs.io`

## Test

```console
$ npm install -g is-http2-cli

$ is-http2 ipfs.io
✓ HTTP/2 supported by ipfs.io
Supported protocols: h2 http/1.1

$ is-http2 node0.delegate.ipfs.io
× HTTP/2 not supported by node0.delegate.ipfs.io
Supported protocols: http/1.1
```

## Motivation

Preload/delegate (https://github.com/ipfs/js-ipfs/issues/2155) hosts receive multiple parallel requests from js-ipfs running in browser context. Browsers limit the number of concurrent requests/connections to ~6.

In HTTP/2 requests are multiplexed on a single connection, which improves performance and removes the amount of requests being in pending state.

**Comment by mburns** [comment]
This is live.

```
mburns@rialto:~)$ sudo /usr/bin/is-http2 node0.delegate.ipfs.io
✓ HTTP/2 supported by node0.delegate.ipfs.io
Supported protocols: h2 http/1.1
```
