### ISSUE TITLE
Binary Hosting Causes Intermittent Failure

### ISSUE THREAD

**Issue by Stebalien** [ipfs/infra#490]
See: https://github.com/ipfs/npm-go-ipfs/issues/22#issuecomment-517462386

**Comment by Stebalien** [comment]
@OR13

Could you run:

```bash
curl https://dist.ipfs.io/go-ipfs/versions
```
?

**Comment by OR13** [comment]
```
› curl https://dist.ipfs.io/go-ipfs/versions
v0.3.2
v0.3.4
v0.3.5
v0.3.6
v0.3.7
v0.3.8
v0.3.9
v0.3.10
v0.3.11
v0.4.0
v0.4.1
v0.4.2
v0.4.3
v0.4.4
v0.4.5
v0.4.6
v0.4.7
v0.4.8
v0.4.9
v0.4.10
v0.4.11
v0.4.12
v0.4.13
v0.4.14
v0.4.15
v0.4.16
v0.4.17
v0.4.18
v0.4.19
v0.4.20
v0.4.21-rc1
v0.4.21-rc3
v0.4.21
v0.4.22-rc1
```

it succeeds

**Comment by OR13** [comment]
Seems like its no longer happening, I had a CI build that failed which I think might be related, but after restarting the build it seems to have installed fine.

**Comment by OR13** [comment]
Still happening.
curl succeeds, but

```
> go-ipfs-dep@0.4.21 install /Users/PROJECT/packages/functions/node_modules/go-ipfs-dep
> node src/bin.js

FetchError: request to https://dist.ipfs.io/go-ipfs/versions failed, reason: unable to verify the first certificate
Download failed!
```

**Comment by OR13** [comment]
intermittent failure, unclear why.

**Comment by Stebalien** [comment]
So, we have multiple gateways and you may have been bouncing between them. However, there was some chatter on the infra channels about cert issues (we were including a partial chain which worked with browsers but not some tools).

@gmasgras sound right to you?

**Comment by gmasgras** [comment]
Yep, one of our gateways in ams1 had an incomplete cert that caused some tools on Linux to fail SSL verification. 
All gateways should be fixed now

**Comment by mburns** [comment]
@OR13 a lot has changed since August, both on the Gateway and across the IPFS network. Are you still hitting this issue, or has it become but a distant memory?

**Comment by OR13** [comment]
Seems resolved, you should close.
