### ISSUE TITLE
Create DNSLink for en.wikipedia-on-ipfs.org

### ISSUE THREAD

**Issue by lidel** [ipfs/infra#491]
https://tr.wikipedia-on-ipfs.org exists 
https://en.wikipedia-on-ipfs.org does not

We will [introduce automation in the future](https://github.com/ipfs/distributed-wikipedia-mirror/issues/58), but for now, as quick fix we should set up DNSLink manually at `en.wikipedia-on-ipfs.org` and point at the latest snapshot `/ipfs/QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco`

Refs. up-to-date list of snapshots: https://github.com/ipfs/distributed-wikipedia-mirror/blob/master/snapshot-hashes.yml

**Comment by mburns** [comment]
https://en.wikipedia-on-ipfs.org/ WFM

**Comment by momack2** [comment]
woohoo! Thanks team! optimistically closing this since seems to be complete AFAICT - reopen if there is something missing!
