### ISSUE TITLE
Circle CI not deploying blog posts

### ISSUE THREAD

**Issue by autonome** [ipfs/infra#492]
## Description

New blog posts for blog.ipfs.io are being built but not deployed.

Twin issue in ipfs/blog: https://github.com/ipfs/blog/issues/312

## Context

Blog no deploy

## Proposal

Deploy the blog plz. Halp.

**Comment by autonome** [comment]
Blog is back up, but there are weeks of failed jobs due to permissions failures. We need to figure out why that's happening so that anyone with push permissions to ipfs/blog can deploy.

https://circleci.com/gh/ipfs/workflows/blog/tree/master

**Comment by autonome** [comment]
I was able to manually kick off a job last week, but now I'm being denied permission.

It's not strictly a permissions issue, because the job history shows the same people having jobs both succeed and fail due to permissions errors.

**Comment by mburns** [comment]
This has been resolved. Please reopen if an issue comes up again
