### ISSUE TITLE
Install the Ajax panel in our Grafana

### ISSUE THREAD

**Issue by autonome** [ipfs/infra#497]
## Description

Oli gave me god permissions on Grafana but installing this panel from the web UI doesn't work.

https://grafana.com/grafana/plugins/ryantxu-ajax-panel

Can someone who knows Grafana install the panel manually?

## Context

IPFS team has a EOQ requirement to wire up important metrics to Grafana, and this panel will make it so they don't have to muck about with moving data around or even learning Grafana at all, and instead can report it from where it currently lay, significantly reducing the barriers for getting these metrics reported in one place.

**Comment by lanzafame** [comment]
@autonome I have installed via the webui. 
<img width="312" alt="Screen Shot 2020-03-16 at 09 49 59" src="https://user-images.githubusercontent.com/5924712/76713319-86443500-676b-11ea-80ba-955ec638745e.png">

**Comment by autonome** [comment]
🙏🏼 thank you!!! confirmed it shows up for me in the plugin list.
