### ISSUE TITLE
node0.preload.ipfs.io NET::ERR_CERT_COMMON_NAME_INVALID

### ISSUE THREAD

**Issue by SignpostMarv** [ipfs/infra#498]
## Description
node0.preload.ipfs.io is being served a certificate issued to *.preload.stage.ipfs.io

## Context

js-ipfs dumps a bunch of errors

## Proposal

* re-issue the certificate **or**
* push out a release of the various libs that uses different domain names

**Comment by SignpostMarv** [comment]
seems to be fixed now.

**Comment by mburns** [comment]
Thanks @SignpostMarv, this caught a failed deploy that was reverted.
