### ISSUE TITLE
Update dist.ipfs.io DNS

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/infra#501]
## Description

Please update the DNS for dist.ipfs.io to account for updates ... 
- PR: https://github.com/ipfs/distributions/pull/289
- Hash: QmRREYVtsPWsjhyxVVydtW9xe9s8NBw2BFfrbNyHcYZGUb

**Comment by jessicaschilling** [comment]
cc @Stebalien @momack2

**Comment by gmasgras** [comment]
Updated in https://github.com/protocol/infra/pull/520
```
;; ANSWER SECTION:
_dnslink.dist.ipfs.io.  60      IN      TXT     "dnslink=/ipfs/QmRREYVtsPWsjhyxVVydtW9xe9s8NBw2BFfrbNyHcYZGUb"
```
